server:
  port: 0

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alurafood-payments?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: payments-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka

resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s